### ISSUE TITLE
Cannot filter on "water/ion" for gro files

### ISSUE THREAD

**Issue by pierrepo** [MDverse/mdde#8]
In the "GRO files" tab, one cannot filter data based on the "water/ion" column.

**Comment by pierrepo** [comment]
@Moohmoo could please have a look at it?

**Comment by Moohmoo** [comment]
@pierrepo I corrected the error. It was also happening on all pages. Thanks for finding it.

**Comment by pierrepo** [comment]
You're welcome. Many thanks for your help.
